name: CI
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    analyze:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                cache: true
            - name: Get dependencies
              run: |
                flutter pub get
                flutter analyze
                dart format --set-exit-if-changed .
                flutter test
    build-android:
        needs: analyze
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                cache: true
            - name: Build Android appbundle
              run: flutter build appbundle --debug 
    build-ios:
      needs: analyze
      runs-on: macos-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              cache: true
          - name: Build ios
            run: flutter build ios --debug --no-codesign 
    build-web:
      needs: analyze
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              cache: true
          - name: Build web
            run: flutter build web
    build-linux:
      needs: analyze
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Linux prerequisites
            run: |
              sudo apt-get update -y
              sudo apt-get install -y ninja-build libgtk-3-dev
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              cache: true
          - name: Build linux
            run: flutter build linux --debug
    build-windows:
      needs: analyze
      runs-on: windows-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              cache: true
          - name: Build windows
            run: flutter build windows --debug
    #build-macos:
    #  needs: analyze
    #  runs-on: macos-latest
    #  steps:
    #      - name: Checkout
    #        uses: actions/checkout@v4
    #      - name: Set up Flutter
    #        uses: subosito/flutter-action@v2
    #        with:
    #          cache: true
    #      - name: Build macos
    #        run: flutter build macos --debug